[package]
name = "tailscale-dmenu"
version = "1.0.0"
edition = "2021"
authors = ["Cyril Levis"]
categories = ["command-line-utilities", "network-programming"]
keywords = ["tailscale", "mullvad", "dmenu", "networking", "linux"]
description = "A simple dmenu-based selector to manage Tailscale exit nodes and custom actions."
readme = "README.md"
license = "ISC"
homepage = "https://github.com/cyrinux/tailscale-dmenu"
repository = "https://github.com/cyrinux/tailscale-dmenu"

[dependencies]
dirs = "4.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
regex = "1"
