[package]
name = "network-dmenu"
version = "1.8.0"
edition = "2021"
authors = ["Cyril Levis"]
categories = ["gui"]
keywords = ["tailscale", "dmenu", "network", "vpn", "wifi"]
description = "A dmenu-based Tailscale and Wi-Fi network selector with support for NetworkManager and iwd."
readme = "README.md"
license = "MIT"
homepage = "https://github.com/cyrinux/network-dmenu"
repository = "https://github.com/cyrinux/network-dmenu"

[dependencies]
dirs = { version = "~6.0" }
serde = { version = "1", default-features = false }
serde_json = "1"
toml = { version = "~0.9", features = ["parse", "serde"], default-features = false }
regex = { version = "~1.11", default-features = false }
reqwest = { version = "~0.12", features = ["blocking", "default-tls", "charset", "json"], default-features = false }
notify-rust = { version = "4", features = ["default"], default-features = false }
which = { version = "~8.0" }
clap = { version = "4", features = [
  "suggestions",
  "help",
  "usage",
  "color",
  "derive",
  "std",
], default-features = false }
ipaddress = "~0.1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "time", "process", "io-util"] }
webbrowser = "1.0.3"
reqwest-middleware = "0.4.2"
reqwest-retry = "0.7.0"
country-emoji = "0.2.0"
once_cell = "1.19"

[dev-dependencies]
mockall = "0.12"
tokio-test = "0.4"
tempfile = "3.8"
