[package]
name = "tailscale-dmenu"
version = "1.0.0"
edition = "2021"
authors = ["Cyril Levis"]
categories = ["network::security", "utilities"]
keywords = ["tailscale", "dmenu", "network", "vpn", "wifi"]
description = "A dmenu-based Tailscale and Wi-Fi network selector with support for NetworkManager and iwd."
readme = "README.md"
license = "MIT"
homepage = "https://github.com/cyrinux/tailscale-dmenu"
repository = "https://github.com/cyrinux/tailscale-dmenu"

[dependencies]
dirs = "4.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
regex = "1.5"
reqwest = { version = "0.11", features = ["blocking", "json"] }

[features]
default = ["networkmanager"]
networkmanager = []
iwd = []
