# General settings
dmenu_cmd = "dmenu"
dmenu_args = "-f --no-multi -f --bind='alt-t:change-query('tailscale')' -f --bind='alt-w:change-query('wifi')' -f --bind='alt-m:change-query('mullvad')' -f --bind='alt-b:change-query('bluetooth')' -f --bind='alt-s:change-query('sign')' -f --bind='alt-e:change-query('exit-node')' -f --bind='alt-v:change-query('vpn')' -f --bind='alt-d:change-query('diagnostic')'"

# DNS cache feature (automatically use fastest DNS from benchmark)
# Set to false to disable cached DNS actions
use_dns_cache = true

# NextDNS configuration (no CLI required - uses API)
# Get your API key from: https://my.nextdns.io/account
# With API key, you can list and switch between all your profiles
nextdns_api_key = "YOUR_API_KEY_HERE"

# Quick toggle between two specific NextDNS profiles (optional)
# Works even without API key if you know the profile IDs
# Find your profile IDs at: https://my.nextdns.io
# Example: Home/Work switching
# nextdns_toggle_profiles = ["abc123", "xyz789"]

# Exit node filtering options
# List of exit nodes to exclude
# exclude_exit_node = ["exit1", "exit2"]

# Limit the number of exit nodes shown per country (sorted by priority)
# max_nodes_per_country = 2

# Limit the number of exit nodes shown per city (sorted by priority)
# max_nodes_per_city = 1

# Filter by country name (e.g., "USA", "Sweden", "Japan")
# country_filter = "USA"

[[actions]]
display = "📡 DNS: Use DHCP server"
cmd = "sudo resolvectl revert wlan0"

[[actions]]
display = "📡 DNS: Use 1.1.1.1 server"
cmd = "sudo resolvectl dns wlan0 '1.1.1.1#cloudflare-dns.com'; sudo resolvectl dnsovertls wlan0 yes"

[[actions]]
display = "📡 DNS: Use Hagezi's server"
cmd = "sudo resolvectl dns wlan0 '76.76.2.11#x-hagezi-ultimate.freedns.controld.com'; sudo resolvectl dnsovertls wlan0 yes"
