# Example configuration file showing SSH SOCKS proxy management
# Place this in ~/.config/network-dmenu/config.toml

dmenu_cmd = "dmenu"
dmenu_args = "-i -l 20"

# SSH SOCKS proxy configurations
[ssh_proxies]

[ssh_proxies.server1]
name = "server1"
server = "example.com"
port = 1081
socket_path = "/tmp/server1.sock"
ssh_options = ["-f", "-q", "-N"]

[ssh_proxies.vpn-server]
name = "vpn-server"
server = "vpn.company.com"
port = 1082
socket_path = "/tmp/vpn-server.sock"
ssh_options = ["-f", "-q", "-N", "-C"]

[ssh_proxies.bastion]
name = "bastion"
server = "bastion.internal"
port = 1083
socket_path = "/tmp/bastion.sock"
ssh_options = ["-f", "-q", "-N", "-o", "StrictHostKeyChecking=no"]

# Example custom actions
[[actions]]
display = "🌐 Configure Firefox Proxy"
cmd = "firefox -preferences"

[[actions]]
display = "🔧 Check SOCKS Connection"
cmd = "curl --socks5 127.0.0.1:1081 httpbin.org/ip"